
spring:
  application:
    name: card
  h2:
    console:
      enabled: true
  datasource:
    username: admin
    password: ""
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9000
