
spring:
  application:
    name: card
  h2:
    console:
      enabled: true
  datasource:
    username: admin
    password: ""
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  config:
    import:
      - application_prod.yml
      - application_qa.yml

  profiles:
    active: qa

server:
  port: 9000

build:
  version: "1.0"

card:
  message: Welcome to EazyBank Card related local APIs
  contactDetails:
    name: John Doe - Developer
    email: john@eazybank.com
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
