spring:
  application:
    name: card
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/carddb
    username: root
    password: root
    show-sql: true
  sql:
    init:
      mode: always

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  
  profiles:
    active: prod

  config:
    import: "optional:configserver:http://localhost:8071/"
#  optional:configserver:http://localhost:8071/ where the configuration is not so important

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
